export const CATEGORIES = {
    SHARE_CERTIFICATE_LINKEDIN: 'share_certificate_linkedin',
    PREVIEW_VIDEO: 'preview_video',
    WEBSITE_NAVIGATION: 'website_navigation',
    PURCHASE_NOW: 'purchase_now',
    PAY_COURSE: 'pay_course',
    THEORY_LAB: 'theory_lab',
    QUIZ: 'quiz',
    TIMING: 'timing',
    REQUEST_COURSE_ACCESS: 'request_course_access',
    HANDS_ON_LAB: 'hands_on_lab',
    LOGIN_BUTTON: 'login_button',
    USER_SIGN_UP: 'user_signup',
    NEWSLETTER: 'newsletter',
    RESET_PASSWORD: 'reset_password',
    COURSE_SELECTION: 'course_selection',
};

export const ACTIONS = {
    USER_CLICKED_SHARE_CERTIFICATE_LINKEDIN_FOR_INTRO_101_BADGE: () => 'User clicked "share certificate" on linkedin for intro 101 badge',
    USER_CLICKED_SHARE_CERTIFICATE_LINKEDIN_AFTER_FINISHING_COURSE: () => 'User clicked "share certificate" on linkedin after finishing a course',
    PREVIEW_VIDEO_OF_COURSE_STARTED: dataTitle => `Preview Video of course ${dataTitle} started`,
    ACCESSED_DENNIS_PAGE: () => 'Accessed Dennis page',
    ACCESSED_SARAH_PAGE: () => 'Accessed Sarah page',
    ACCESSED_INTRODUCTION_TOUR_PAGE: () => 'Accessed introduction tour page',
    PURCHASE_COURSE: dataTitle => `Purchase course ${dataTitle}`,
    PAY_COURSE: dataTitle => `Pay Course ${dataTitle}`,
    THEORY_STARTED_FOR_COURSE: dataTitle => `Theory started for course ${dataTitle}`,
    QUIZ_STARTED_FOR_COURSE: dataTitle => `Quiz started for course ${dataTitle}`,
    REQUEST_ACCESS_FOR_COURSE: dataTitle => `Request Access for course ${dataTitle}`,
    HAND_ON_LAB_STARTED_FOR_COURSE_FROM_ACTIVE_LAB: dataTitle => `Hands-on Lab started for course ${dataTitle}`,
    LOGIN_BUTTON_CLICKED: () => 'Login Button clicked',
    USER_CLICKED_REGISTER_NOW: () => 'User clicked register now',
    USER_CONFIGURED_MFA: () => 'User configured MFA',
    USER_FAILED_TO_SIGN_UP: () => 'User failed to sign up',
    USER_SUBMITTED_DETAILS_TO_REGISTER: () => 'User submitted details to register',
    HANDS_ON_LAB_STARTED_FOR_COURSE_FROM_ACTIVE_COURSE: dataTitle => `Hands-on Lab started for course ${dataTitle}`,
    ACCESSED_FELLOWSHIP_PAGE: () => 'Accessed fellowship page',
    USER_SUBSCRIBED: () => 'User subscribed',
    ACCESSED_BUSINESS_PAGE: () => 'Accessed business page',

    // RESET_PASSWORD
    RESET_PASSWORD_FAIL: () => 'No email has been entered',
    RECAPTCHA_ACTIVATED: () => 'Recaptcha was successfull',
    RECAPTCHA_ACTIVATED_FAIL: () => 'Recaptcha has failed',
    RESET_LINK_FROM_EMAIL: () => 'Instructions followed',
    PASSWORD_CHANGED: () => 'Password has been changed succesfully',
    // CATEGORY: COURSE_SELECTION
    OPEN_COURSE: dataTitle => `Open course ${dataTitle}`,
    CLICKED_ON_LEARNING_PATH: dataTitle => `Clicked on ${dataTitle} learning path`,
    INTRODUCTION_MODULE_LAB_CREATED: () => 'Introduction module lab created for',
};
