export const GET_ACTIVE_COURSE_START = 'GET_ACTIVE_COURSE_START';
export const GET_ACTIVE_COURSE_SUCCESS = 'GET_ACTIVE_COURSE_SUCCESS';
export const GET_ACTIVE_COURSE_ERROR = 'GET_ACTIVE_COURSE_ERROR';
