export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FILED = 'AUTH_FILED';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_AUTH_USER = 'GET_AUTH_USER';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';
export const UPDATE_AUTH_USER_ACTIVE_LAB = 'UPDATE_AUTH_USER_ACTIVE_LAB';
export const UPDATE_AUTH_USER_ACTIVE_LAB_DURATION = 'UPDATE_AUTH_USER_ACTIVE_LAB_DURATION';
export const GET_QR_CODE_SUCCESS = 'GET_QR_CODE_SUCCESS';
