export const SHARE_CERTIFICATE_EMAIL_START = 'SHARE_CERTIFICATE_EMAIL_START';
export const SHARE_CERTIFICATE_EMAIL_SUCCESS = 'SHARE_CERTIFICATE_EMAIL_SUCCESS';
export const SHARE_CERTIFICATE_EMAIL_ERROR = 'SHARE_CERTIFICATE_EMAIL_ERROR';
export const FETCH_USER_CERTIFICATES = 'FETCH_USER_CERTIFICATES';
export const GET_PUBLIC_CERTIFICATE_BY_ID = 'GET_PUBLIC_CERTIFICATE_BY_ID';
export const GET_USER_CERTIFICATE_BY_ID = 'GET_USER_CERTIFICATE_BY_ID';
