export const GET_CHAPTERS_START = 'GET_CHAPTERS_START';
export const GET_CHAPTERS_SUCCESS = 'GET_CHAPTERS_SUCCESS';
export const GET_CHAPTERS_ERROR = 'GET_CHAPTERS_ERROR';
export const SAVE_CURRENT_STEP = 'SAVE_CURRENT_STEP';
