export const FETCH_COURSES_START = 'FETCH_COURSES_START';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_ERROR = 'FETCH_COURSES_ERROR';

export const GET_COURSE_START = 'GET_COURSE_START';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const GET_AWS_LINK_SUCCESS = 'GET_AWS_LINK_SUCCESS';

export const FETCH_INTRO_COURSES = 'FETCH_INTRO_COURSES';
export const FETCH_COURSES_GROUPED_BY_TYPES = 'FETCH_COURSES_GROUPED_BY_TYPES';
