export const FETCH_FELLOW_COURSES = 'FETCH_FELLOW_COURSES';
export const GET_DESIRED_COURSES = 'GET_DESIRED_COURSE';
export const CREATE_COURSE_PROPOSAL = 'CREATE_COURSE_PROPOSAL';
export const GET_PROPOSALS = 'GET_PROPOSALS';
