export const FETCH_LABS_START = 'FETCH_LABS_START';
export const FETCH_LABS_SUCCESS = 'FETCH_LABS_SUCCESS';
export const FETCH_LABS_ERROR = 'FETCH_LABS_ERROR';

export const CREATE_LAB_START = 'CREATE_LAB_START';
export const CREATE_LAB_SUCCESS = 'CREATE_LAB_SUCCESS';
export const CREATE_LAB_ERROR = 'CREATE_LAB_ERROR';

export const DESTROY_LAB_START = 'DESTROY_LAB_START';
export const DESTROY_LAB_SUCCESS = 'DESTROY_LAB_SUCCESS';
export const DESTROY_LAB_ERROR = 'DESTROY_LAB_ERROR';

export const GET_ACTIVE_LAB_START = 'GET_ACTIVE_LAB_START';
export const GET_ACTIVE_LAB_SUCCESS = 'GET_ACTIVE_LAB_SUCCESS';
export const GET_ACTIVE_LAB_ERROR = 'GET_ACTIVE_LAB_ERROR';

export const GET_JOB_PROGRESS = 'GET_JOB_PROGRESS';
export const SAVE_CURRENT_LAB_STEP = 'SAVE_CURRENT_LAB_STEP';
export const UPDATE_HINTS_OPEN = 'UPDATE_HINTS_OPEN';
export const GET_REMAINING_HINTS_COUNT = 'GET_REMAINING_HINTS_COUNT';

export const EDIT_RESOURCE_URL_STATUS = 'EDIT_RESOURCE_URL_STATUS';

export const SAVE_STEP_PROGRESS = 'SAVE_STEP_PROGRESS';
