export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_UNREAD_NOTIFICATIONS = 'GET_UNREAD_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_UNREAD_NOTIFICATION = 'ADD_UNREAD_NOTIFICATION';
export const NOTIFICATIONS_SEEN = 'NOTIFICATIONS_SEEN';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const NOTIFICATION_SEEN = 'NOTIFICATION_SEEN';
