export const ADMIN_FETCH_ACTIVE_LAB_HISTORY = 'ADMIN_FETCH_ACTIVE_LAB_HISTORY';
export const ADMIN_DESTROY_ACTIVE_LAB = 'ADMIN_DESTROY_ACTIVE_LAB';
export const ADMIN_RECREATE_ACTIVE_LAB = 'ADMIN_RECREATE_ACTIVE_LAB';
export const ADMIN_SET_ACTIVE_LAB_DURATION = 'ADMIN_SET_ACTIVE_LAB_DURATION';
export const ADMIN_CHANGE_PROGRESS = 'ADMIN_CHANGE_PROGRESS';
export const ADMIN_FETCH_ACTIVE_LAB = 'ADMIN_FETCH_ACTIVE_LAB';
