export const GET_COURSE_BY_ID_START = 'GET_COURSE_BY_ID_START';
export const GET_COURSE_BY_ID_ERROR = 'GET_COURSE_BY_ID_ERROR';
export const GET_COURSE_BY_ID_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const ADMIN_FETCH_COURSE_TEMPLATE = 'ADMIN_FETCH_COURSE_TEMPLATE';

export const UPDATE_COURSE = 'UPDATE_COURSE';
export const CREATE_COURSE = 'CREATE_COURSE';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADMIN_FETCH_CATEGORY = 'ADMIN_FETCH_CATEGORY';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';

export const ADMIN_ADD_NEW_LAB = 'ADMIN_ADD_NEW_LAB';
export const ADMIN_UPDATE_LAB = 'ADMIN_UPDATE_LAB';
export const ADMIN_DELETE_LAB = 'ADMIN_DELETE_LAB';

export const ADMIN_UPDATE_QUIZ = 'ADMIN_UPDATE_QUIZ';
export const ADMIN_CREATE_QUIZ = 'ADMIN_CREATE_QUIZ';
export const ADMIN_DELETE_QUIZ = 'ADMIN_DELETE_QUIZ';
export const ADMIN_SAVE_ALL_QUIZZES = 'ADMIN_SAVE_ALL_QUIZZES';

export const SIGN_LAB = 'SIGN_LAB';
export const ADD_AUTHOR = 'ADD_AUTHOR';
export const REMOVE_AUTHOR = 'REMOVE_AUTHOR';

export const ADMIN_ADD_HINT = 'ADMIN_ADD_HINT';
export const ADMIN_EDIT_HINT = 'ADMIN_EDIT_HINT';
export const ADMIN_DELETE_HINT = 'ADMIN_DELETE_HINT';

export const ADMIN_FETCH_COURSE_DESIGNS = 'ADMIN_FETCH_COURSE_DESIGNS';

export const ADMIN_FETCH_COURSE_TYPES = 'ADMIN_FETCH_COURSE_TYPES';
