export const ADMIN_GET_JOBS_START = 'ADMIN_GET_JOBS_START';
export const ADMIN_GET_JOBS_SUCCESS = 'ADMIN_GET_JOBS_SUCCESS';
export const ADMIN_GET_JOBS_ERROR = 'ADMIN_GET_JOBS_ERROR';

export const ADMIN_DELETE_JOB = 'ADMIN_DELETE_JOB';
export const ADMIN_CHANGE_JOB_STATUS = 'ADMIN_CHANGE_JOB_STATUS';
export const ADMIN_BULK_DELETE_JOBS = 'ADMIN_BULK_DELETE_JOBS';
