export const ADMIN_FETCH_CERTIFICATES = 'ADMIN_FETCH_CERTIFICATES';
export const ADMIN_DELETE_CERTIFICATE = 'ADMIN_DELETE_CERTIFICATE';
export const ADMIN_UPDATE_CERTIFICATE = 'ADMIN_UPDATE_CERTIFICATE';
