export const ADMIN_ADD_POST = 'ADMIN_ADD_POST';
export const ADMIN_FETCH_POSTS = 'ADMIN_FETCH_POSTS';
export const ADMIN_REMOVE_POST = 'ADMIN_REMOVE_POST';
export const ADMIN_UPDATE_POST = 'ADMIN_UPDATE_POST';
