export const ADMIN_GET_ACCESS_REQUESTS_SUCCESS = 'ADMIN_GET_ACCESS_REQUESTS_SUCCESS';
export const ADMIN_CHANGE_REQUEST_STATUS_SUCCESS = 'ADMIN_CHANGE_REQUEST_STATUS_SUCCESS';
export const ADMIN_DELETE_REQUEST = 'ADMIN_DELETE_REQUEST';
