export const ADMIN_FETCH_SETTINGS = 'ADMIN_FETCH_SETTINGS';
export const ADMIN_CREATE_FAQ = 'ADMIN_CREATE_FAQ';
export const ADMIN_UPDATE_FAQ = 'ADMIN_UPDATE_FAQ';
export const ADMIN_DELETE_FAQ = 'ADMIN_DELETE_FAQ';
export const ADMIN_UPDATE_RIGHT_SIDE_BAR_CONTENT = 'ADMIN_UPDATE_RIGHT_SIDE_BAR_CONTENT';
export const ADMIN_UPDATE_CTO_SETTINGS = 'ADMIN_UPDATE_CTO_SETTINGS';
