export const ADMIN_FETCH_USERS_START = 'ADMIN_FETCH_USERS_START';
export const ADMIN_FETCH_USERS_SUCCESS = 'ADMIN_FETCH_USERS_SUCCESS';
export const ADMIN_FETCH_USERS_ERROR = 'ADMIN_FETCH_USERS_ERROR';

export const ADMIN_DELETE_USER_START = 'ADMIN_DELETE_USER_START';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_ERROR = 'ADMIN_DELETE_USER_ERROR';

export const ADMIN_CHANGE_USER_STATUS_START = 'ADMIN_CHANGE_USER_STATUS_START';
export const ADMIN_CHANGE_USER_STATUS_SUCCESS = 'ADMIN_CHANGE_USER_STATUS_SUCCESS';
export const ADMIN_CHANGE_USER_STATUS_ERROR = 'ADMIN_CHANGE_USER_STATUS_ERROR';

export const ADMIN_CREATE_USER = 'ADMIN_CREATE_USER';
export const ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER';

export const ADMIN_CHANGE_FELLOW = 'ADMIN_CHANGE_FELLOW';
